(define (game::new)
 (let* ((engine (engine::new screen-width screen-height))
       (game-mode-selector (game-mode-selector::new 'test engine)))
  
  (define (start!)
    (let ((draw-update (game-mode-selector 'get-draw-update))
         (logic-update (game-mode-selector 'get-logic-update)))
           (engine::initialise-draw-callback! engine draw-update)
           (engine::initialise-update-callback! engine logic-update)))
  
  (define (dispatch-game message . args)
    (cond ((eq? message 'test) args)
          ((eq? message 'start!) (start!))
          (else (error "game ADT unkown message" message))))
  dispatch-game))